SecurityGroupPorts:
- 80
RuntimeType: Container
ServicePorts:
- 80
ServiceType: private
ArtifactSourceType: Buildpacks
RepoName: aliyun-computenest/python-falcon-demo
ServiceBuildRegion: ap-southeast-1
RegionId: cn-hangzhou
CustomParameters:
- liuzheng: test
Owner: workhardliuzheng
Branch: main
Platform: github
